services:
  - type: web
    name: user-auth-service
    env: python
    region: singapore
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DB_HOST
        value: ""
      - key: DB_USER
        value: ""
      - key: DB_PASSWORD
        value: ""
      - key: DB_NAME
        value: ""
